Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

