# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7430a63707f4ba09754cd572a7f580e619a4c13e57b6c59b6d54381759f717df53568c5d7873a54207da4e0dbbf7a95a7933822d49dcfa8adddf0424f15449d9

test:
  secret_key_base: e46056ceccbcb757ad4e3500933f6b2153f857cb284e97bef23cc4448665eb8ae7f3125f8417d7e1ed8ed27a39cb502651ce74646913eec2f471988ba9e6a90b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
